// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDICl7CY0kjk5XZLtKYH60-A7ZPTNG_VSg',
    appId: '1:1086037628788:web:357b4dc90ef5e688137e21',
    messagingSenderId: '1086037628788',
    projectId: 'smc041024',
    authDomain: 'smc041024.firebaseapp.com',
    storageBucket: 'smc041024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTD096rivXkty9JMUwZEYBApDjvNgHkSQ',
    appId: '1:1086037628788:android:59f9723bb6486934137e21',
    messagingSenderId: '1086037628788',
    projectId: 'smc041024',
    storageBucket: 'smc041024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFwsXSuZtWEpjECIh4hV61YP7dXAivb_k',
    appId: '1:1086037628788:ios:34a4c75d83cff7ff137e21',
    messagingSenderId: '1086037628788',
    projectId: 'smc041024',
    storageBucket: 'smc041024.appspot.com',
    iosBundleId: 'com.example.smc041024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFwsXSuZtWEpjECIh4hV61YP7dXAivb_k',
    appId: '1:1086037628788:ios:34a4c75d83cff7ff137e21',
    messagingSenderId: '1086037628788',
    projectId: 'smc041024',
    storageBucket: 'smc041024.appspot.com',
    iosBundleId: 'com.example.smc041024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDICl7CY0kjk5XZLtKYH60-A7ZPTNG_VSg',
    appId: '1:1086037628788:web:bfe3572da0733c24137e21',
    messagingSenderId: '1086037628788',
    projectId: 'smc041024',
    authDomain: 'smc041024.firebaseapp.com',
    storageBucket: 'smc041024.appspot.com',
  );
}
